# .github/workflows/deploy-frontend.yml

name: Deploy Static Frontend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'logo.png'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. scp를 사용해 EC2 서버의 Nginx root 경로로 직접 파일 전송
      - name: Transfer files to EC2
        uses: appleboy/scp-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html,logo.png" # 쉼표로 여러 파일 지정
          target: "/usr/share/nginx/html/"
          overwrite: true # 기존 파일 덮어쓰기
