name: Deploy Frontend to EC2

on:
  # main 브랜치에 푸시될 때마다 실행됩니다.
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소의 코드를 Runner로 가져옵니다.
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. 배포에 불필요한 .git, .github 폴더를 삭제합니다.
      #    이 단계를 통해 scp-action에서 발생하던 파일 권한 오류를 원천적으로 방지합니다.
      - name: Remove unnecessary directories
        run: |
          rm -rf .git
          rm -rf .github

      # 3. 정리된 파일들을 EC2 서버의 Nginx root 경로로 전송합니다.
      - name: Transfer Files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "." # 불필요한 파일이 제거된 현재 폴더 전체를 의미
          target: "/usr/share/nginx/html"
          overwrite: true
