name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Transfer All Files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."  
          target: "/usr/share/nginx/html"
          overwrite: true
